version: "3.8"

services:
  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secure_password
    volumes:
      - mongodb_data:/data/db
    networks:
      - cost-network

  socket-backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8001:8001"
    environment:
      - MONGODB_URI=mongodb://admin:secure_password@mongodb:27017
      - MONGODB_DATABASE=cost
      - WEBSOCKET_PORT=8001
    depends_on:
      - mongodb
    networks:
      - cost-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:80"
    depends_on:
      - socket-backend
    networks:
      - cost-network

volumes:
  mongodb_data:

networks:
  cost-network:
    driver: bridge
